-- Projects Table
create table public.projects (
  id bigint generated by default as identity primary key,
  title text not null,
  category text not null,
  status text not null default 'pending', -- 'active' or 'pending'
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Messages Table
create table public.messages (
  id bigint generated by default as identity primary key,
  name text not null,
  email text not null,
  message text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable Row Level Security (RLS)
alter table public.projects enable row level security;
alter table public.messages enable row level security;

-- Policies (For demonstration purposes, allowing public read/write. In production, lock this down!)
-- Projects: Public read, Authenticated write
create policy "Public projects are viewable by everyone"
  on public.projects for select
  using ( true );

create policy "Authenticated users can insert projects"
  on public.projects for insert
  with check ( auth.role() = 'authenticated' );

create policy "Authenticated users can update projects"
  on public.projects for update
  using ( auth.role() = 'authenticated' );

create policy "Authenticated users can delete projects"
  on public.projects for delete
  using ( auth.role() = 'authenticated' );

-- Messages: Public insert (contact form), Authenticated read
create policy "Everyone can insert messages"
  on public.messages for insert
  with check ( true );

create policy "Authenticated users can view messages"
  on public.messages for select
  using ( auth.role() = 'authenticated' );
